name: Installation testing

on:
  push:
    branches:
    - installation-workflow
    - master

# We set the supported coq-version from here. In order to use this environment variable correctly, look at how they are used in the following jobs.
env:
  coq-version-supported: '8.14'
  ocaml-version: '4.11.x'


jobs:
  install-manual:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , macos-latest , windows-latest ]
    steps:
    - name: Setup OCaml ğŸ« ${{ matrix.ocaml-compiler }}
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ env.ocaml-version }}
    - name: Install Coq ğŸ”
      run: opam update; opam install coq -y
    - name: Build HoTT
      run: make
    - name: Install HoTT ğŸ©
      run: sudo make install

  install-opam:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Setup OCaml ğŸ« ${{ matrix.ocaml-compiler }}
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ env.ocaml-version }}
    - name: Install Coq ğŸ”
      run: opam install -y coq
    - name: Install HoTT ğŸ©
      run: opam install -y .

